# Generated by Django 2.2.6 on 2020-04-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('power_state', models.CharField(max_length=50)),
                ('cpu_count', models.IntegerField()),
                ('memory_size_mib', models.IntegerField()),
            ],
        ),
    ]
