# Generated by Django 2.2.6 on 2020-06-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmManage', '0002_device_members_pool_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itsm_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vip',
            name='create_by_order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmManage.order'),
        ),
    ]
