# Generated by Django 2.2.6 on 2020-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmManage', '0004_auto_20200604_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vip',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
