# Generated by Django 2.2.6 on 2020-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmManage', '0005_auto_20200604_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=50),
        ),
    ]
