# Generated by Django 2.2.6 on 2020-06-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmManage', '0006_auto_20200604_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vmManage.Pool'),
        ),
    ]
