# Generated by Django 2.2.6 on 2020-06-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmManage', '0007_auto_20200608_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ip',
            new_name='mgt_ip',
        ),
    ]
