# Generated by Django 2.2.6 on 2020-06-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmManage', '0009_auto_20200609_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
