# Generated by Django 2.2.6 on 2020-06-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmManage', '0010_auto_20200609_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vip',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vip',
            name='create_by_order_id',
        ),
        migrations.CreateModel(
            name='RequirementVip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.CharField(max_length=50)),
                ('vport', models.IntegerField()),
                ('create_by_order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_order', to='vmManage.order')),
                ('delete_by_order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_order', to='vmManage.order')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmManage.Device')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vmManage.Pool')),
                ('update_by_order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_order', to='vmManage.order')),
            ],
            options={
                'unique_together': {('vip', 'vport')},
            },
        ),
    ]
